## 端口号
server:
  port: 8888
  tomcat:
    max-http-form-post-size: -1
    
spring:
  application:
    name: SPRINGBOOT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url :  jdbc:mysql://bj-cynosdbmysql-grp-qzs817me.sql.tencentcdb.com:27204/elderly_care_back?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowPublicKeyRetrieval=true&&serverTimezone=GMT%2B8
    username : root
    password : Zjq123789
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.back.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
logging:
    # 日志path路径配置
     file:
      path: D:/elderly-care-backend-master/SpringbootServer/eurekaServer
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/ # eureka server