spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: GUYI
          uri: lb://FLASK-SERVER
          predicates:
            - Path=/flask/**
        - id: SPRINGBOOT
          uri: http://localhost:8888
          predicates:
            - Path=/back/**
#          uri: lb://SPRINGBOOT
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka server