server:
  port: 8761

eureka:
  instance:
    hostname: localhost #172.30.86.237
  client:
    registerWithEureka: false
    fetchRegistry: false  #全都改成true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/